module Socrata
  class SocrataAPI
    include HTTParty
  
    default_options[:headers] = {'Content-type' => 'application/json'}
    format :json
  
    attr_reader :error
    attr_reader :config
    
    def initialize(params = {})
      mode = params[:mode] || 'development'
      @config = params[:config] || YAML.load_file(File.dirname(__FILE__) + '/config.yml')[mode]
      
      @logger = params[:logger] || Logger.new(STDOUT)
    
      self.class.basic_auth(@config['credentials']['user'], 
        @config['credentials']['password']) unless @config['credentials'].nil?
      self.class.base_uri @config['server']['host'] unless @config['server'].nil?
      self.class.headers 'X-Socrata-Host' => @config['server']['socrata_host'] unless @config['server']['socrata_host'].nil?
    end
  
    # Process an array of batch requests, generated by get_add_row_request
    def batch_request(batches)
      @response = self.class.post("/batches", :body => {:requests => batches}.to_json)
    end
  
    # Reads @response and checks for error code
    def check_error()
      if !@response.nil? && @response['error']
        @logger.error("Code: #{@response['code']}, Message: #{@response['message']}")
      else
        @response
      end
    end
  end 
end